<?php
$_paymentfee = $this->getFee();
$phone = $this->getPhone();
$_code = $this->getMethodCode(); 
$_description = $this->getInstructions();
?>

	<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none">
		<li class="form-alt">
			<?php
				if($_paymentfee['incl'] > 0)
				{
					echo '<b>'. $this->__(Mage::getStoreConfig('payment/'.$_code.'/payment_fee_label')) .' ' . Mage::app()->getStore()->convertPrice($_paymentfee['incl'], true, true).'</b>';
				}
			?>
			
			<?php 
				if(!empty($_description))
				{
					echo '<p>' . $_description . '</p>';
				}
			?>
			
			<p>
				Je betaalt de  bestelling in drie gelijke termijnen. De eerste termijn betaal je nu direct via iDEAL. Van IN3 ontvang je vervolgens een iDEAL link voor de tweede (dag 30) en derde (dag 60) termijn.
			</p>
			
			<br/>
			<label for="sisow_gender"><?php echo $this->__('Salutation'); ?>&nbsp;<span class="required"></span></label>
			<div class="input-box">
				<select id="sisow_gender" class="input-text required-entry" title="Aanhef" name="payment[sisow_gender]">
					<option value=""><?php echo $this->__('--Please Select--') ?></option>
					<option value="F"><?php echo $this->__('Female');?></option>
					<option value="M"><?php echo $this->__('Male');?></option>
				</select>
			</div>
			<br/>
			<label for="sisow_phone"><?php echo $this->__('Telephone Number');?>&nbsp;<span class="required"></span></label>
			<div class="input-box">
				<input id="sisow_phone" class="input-text required-entry" maxlength="12" title="Telefoonnummer" value="<?php echo $phone; ?>" name="payment[sisow_phone]"/>
			</div>
			<br/>
			<label for="sisow_day"><?php echo $this->__('Date of birth');?>&nbsp;<span class="required"></span></label></br>
			<div class="select">
					<select id="sisow_day" name="payment[sisow_day]" title="sisow_day" class="year required-entry">
						<option value=""><?php echo $this->__('Day');?></option>
						<?php foreach($this->getDates() as $k=>$v){?>
							<option value="<?php echo $k;?>"><?php echo $v;?></option><?php } ?>
					<select>
					<select id="sisow_month" name="payment[sisow_month]" title="sisow_day" class="year required-entry">
						<option value=""><?php echo $this->__('Month');?></option>
						<?php foreach($this->getMonths() as $k=>$v){?>
							<option value="<?php echo $k;?>"><?php echo $v;?></option><?php } ?>
					<select>
					<select id="sisow_year" name="payment[sisow_year]" title="sisow_year" class="year required-entry">
						<option value=""><?php echo $this->__('Year');?></option>
						<?php foreach($this->getYears() as $k=>$v){?>
							<option value="<?php echo $k;?>"><?php echo $v;?></option><?php } ?>
					<select>
			</div>

			<br/>
			<div style="text-align: right; width: 100%;">
				<a target="_blank" href="https://www.payin3.nl/nl/consumenten/hoe-werkt-gespreid-betalen-met-in3/"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . DS . 'sisow' . DS . 'capayable.png'; ?>" alt="Powered by Sisow" width="100px"/></a>
			</div>
		</li>
	</ul>